spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Africa/Casablanca
  jackson:
    time-zone: Africa/Casablanca
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      accept-single-value-as-array: true
server:
  port: 8080
